package:
  name: qrisk
  version: "0.1.6"

source:
  fn: qrisk-0.1.6.tar.gz
  url: https://files.pythonhosted.org/packages/4d/12/dfeda1ab1e6fef89e74c0d89d6d3211685eac6b465ffa30e4632a33ba7a0/qrisk-0.1.6.tar.gz
  md5: 4f5bfb8cd22f0386185097a3f5eb4ee8


requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - pandas >=0.16.1
    - scipy >=0.15.1
    - bottleneck >=1.0.0

  run:
    - python
    - numpy x.x
    - pandas >=0.16.1
    - scipy >=0.15.1
    - bottleneck >=1.0.0


about:
  home: https://github.com/quantopian/qrisk
  license: Apache Software License
  summary: 'qrisk is a Python library with performance and risk statistics\ncommonly used in quantitative finance'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
